[librime-lua]
src.git = "https://github.com/hchunhui/librime-lua.git"
fetch.github = "hchunhui/librime-lua"

[librime-proto]
src.git = "https://github.com/lotem/librime-proto.git"
fetch.github = "lotem/librime-proto"
