{ ... }:
{
  home.sessionVariables = {
    QT_QPA_PLATFORM = "wayland;xcb";
    QT_WAYLAND_DISABLE_WINDOWDECORATION = 1;
    QT_AUTO_SCREEN_SCALE_FACTOR = 1;
    QT_SCALE_FACTOR_ROUNDING_POLICY = "RoundPreferFloor";

    GDK_BACKEND = "wayland,x11";
    GTK_USE_PORTAL = 1;

    SDL_VIDEODRIVER = "wayland";
    _JAVA_AWT_WM_NONREPARENTING = 1;
    CLUTTER_BACKEND = "wayland";

    MOZ_ENABLE_WAYLAND = 1;
    MOZ_ACCELERATED = 1;
    MOZ_WEBRENDER = 1;
  };

  wayland.windowManager.hyprland.systemd.variables = [
    "DISPLAY"
    "HYPRLAND_INSTANCE_SIGNATURE"
    "WAYLAND_DISPLAY"
    "XDG_CURRENT_DESKTOP"
    "QT_QPA_PLATFORM"
    "QT_WAYLAND_DISABLE_WINDOWDECORATION"
    "QT_AUTO_SCREEN_SCALE_FACTOR"
    "QT_SCALE_FACTOR_ROUNDING_POLICY"
    "GDK_BACKEND"
    "GTK_USE_PORTAL"
  ];
}
