#!/usr/bin/env bash
swayidle -w \
    timeout 600 'hyprlock -f'
    timeout 900 'niri msg action power-off-monitors'
    resume 'niri msg action power-on-monitors'
    timeout 1800 'systemctl suspend'
    before-sleep 'hyprlock -f'
