POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs virtualenv rbenv rvm vcs)

POWERLEVEL9K_DIR_PATH_SEPARATOR=" %F{251}$(print_icon 'LEFT_SUBSEGMENT_SEPARATOR')%F{251} "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_from_right'
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

POWERLEVEL9K_STATUS_OK=false

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='240'
POWERLEVEL9K_DIR_HOME_BACKGROUND='240'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='240'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='031'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='052'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='236'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='074'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='251'
POWERLEVEL9K_DIR_HOME_FOREGROUND='251'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='251'
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='255'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='255'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='251' #'156'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='225'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='228'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='255'
