set -g mouse on
set -g mode-keys vi
set -g default-terminal "tmux-256color"
set -sg escape-time 0
set -g focus-events on
set -g base-index 1
setw -g pane-base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind t display-popup -E btop

set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -as terminal-features ',*:RGB'
set -g extended-keys on
set -g extended-keys-format csi-u

set -g status-left " #S | "
set -g window-status-current-format "#[fg=#{@noctalia_primary},bold] ●#[underscore]#I:#W"
set -g window-status-format "#I:#W"

# C-hjkl across tmux panes and nvim splits (nvim-tmux-navigation).
# https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind r source ~/.config/tmux/tmux.conf
source-file -q "$HOME/.config/tmux/themes/noctalia.conf"
